image: registry.gitlab.com/pages/hugo:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

pages:
  script:
    - apk --update add make
    - make
  artifacts:
    paths:
    - public
  only:
  - master
